<?php

namespace Kinash\SportCalendarBundle\Entity;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends EntityRepository
{
    protected $_entityManager;

    /**
     * @param EntityManager $entityManager
     */
    public function __construct(EntityManager $entityManager)
    {
        $this->_entityManager = $entityManager;
    }

    /**
     * @param $userId
     * @param $datesArray array of dates
     * @return array of SportCalendarBundle:Exercise
     */
    public function getTrainingData($user, $datesArray) {
        $criteria = array(
            'date' => $datesArray,
            'user' => $user
        );
        $data = $this->_entityManager->getRepository('SportCalendarBundle:Exercise')->findBy($criteria);
        return $data;


    }
}
